### ISSUE TITLE
Add a landing page

### ISSUE THREAD

**Issue by jimmycuadra** [ruma/ruma.github.io#1]
Add a basic landing page for the root of the website with:
1. The name and tagline (Ruma / Matrix.org components written in Rust.)
2. "What is X?" sections for:
   1. Matrix.org: Emphasize that it's not controlled by a company, that users have control of their own data and communications, that it has all the features of a modern system, and will be extended over time to keep up to date with users' needs as they evolve.
   2. Rust: Emphasize memory safety, security, performance, and the rich type system.
   3. Ruma: Emphasize privacy, security, and scalability.
3. Link to the GitHub organization (ruma) and Twitter account (ruma_io).

Design can be very simple, nothing flashy necessary.

**Comment by rjfranco** [comment]
I'll take a stab at it tonight!

**Comment by jimmycuadra** [comment]
:heart::heart::heart::heart::heart:
