### ISSUE TITLE
More projects for the Projects using Ruma page

### ISSUE THREAD

**Issue by jplatte** [ruma/ruma.github.io#19]
Things that weren't initially on the page but I'd like to have there:

* [ ] https://github.com/lieuwex/matrix-appservice-rs
* [ ] https://github.com/lieuwex/tomsg-matrix
* [x] https://github.com/florianjacob/synadminctl
* [ ] https://github.com/keymaker-mx/keymaker-bot

**Comment by jplatte** [comment]
@lieuwex how is it going? Are you planning to get back to https://github.com/lieuwex/matrix-appservice-rs or https://github.com/lieuwex/tomsg-matrix? If they had some more README info, I would have already included them 🙂

**Comment by jplatte** [comment]
Note to self: ~~Maybe~~ add https://github.com/florianjacob/synadminctl

**Comment by jplatte** [comment]
@MTRNord would be really cool if you could add a readme to https://github.com/keymaker-mx/keymaker-bot, then I'd immediately link to it 🙂

**Comment by zluudg** [comment]
Hello!
I'm writing a small application service called Rumraisin, which is a RSS/Atom-to-Matrix bridge. It has only very basic functionality, but I intend to keep working on it as a pet project and any feedback I get will be much appreciated. I would be very proud and happy if it was included on the Ruma web page!

Repo link: https://gitlab.com/zluudg/rumraisin

Cheers!

**Comment by jplatte** [comment]
Somehow this showed up in my notifications, was there a comment that was deleted? Anyways, this is pretty dated and not really useful anymore.

**Comment by Ruma-w** [comment]
This project is a great example of what can be accomplished using GitHub Pages. I look forward to seeing more contributions and updates in the future!
