### ISSUE TITLE
Twitter account does not exist

### ISSUE THREAD

**Issue by swedgwood** [ruma/ruma.github.io#25]
The link on the home page at `/content/_index.md` leads to a "This account doesn't exist" on Twitter. I'm not sure if the Ruma twitter account has been renamed or deleted, but no matter what it is, this should probably be fixed.

**Comment by jplatte** [comment]
I deleted that account since I'm not a huge fan of Twitter and wasn't maintaining it. I'll remove the link.

**Comment by jplatte** [comment]
Done: https://github.com/ruma/ruma.github.io/commit/76b26d521858ac141bf50df85140badcb3cff3c8
