### ISSUE TITLE
Fix link on github org

### ISSUE THREAD

**Issue by ESHARK22** [ruma/ruma.github.io#27]
It looks like the website changed from `ruma.io` to `ruma.dev`, but the github organisation's url was not updated.

![image](https://github.com/ruma/ruma.dev/assets/115404421/adc8f4c9-5ade-484e-a315-eb91a0450ff9)

**Comment by jplatte** [comment]
Yeah, we're slowly migrating to the new domain, there's a number of things still needing change. Thanks for letting me know about this bit, it wasn't on the radar.

**Comment by jplatte** [comment]
Updated!
