### ISSUE TITLE
Add a page that references downstream projects

### ISSUE THREAD

**Issue by iinuwa** [ruma/ruma.github.io#9]
It might be nice to have a page that shows where Ruma libraries are being used, both for their exposure and ours.

In particular, explicitly stating that matrix-rust-sdk is built on top of Ruma may also help eliminate some confusion about the relationship between the two projects.

**Comment by jplatte** [comment]
Things we should definitely mention:

* matrix-rust-sdk
* Stuff building on top of matrix-rust-sdk
  * Fractal (once they use more of Ruma?)
  * ~~Daydream~~ (not actively developed)
  * Rumatui
  * weechat-matrix-rs
* Conduit

Things we could also mention:

* Sparky's bot (once it has been renamed?)
* dsn-traveler (a bit outdated, but why not?)
* ~~Maelstrom (once they use more of Ruma?)~~ (not actively developed)
* stoic's p2p wasm homeserver (not released yet AFAICT)
* **other projects I'm not aware of or forgot to list?**

**Comment by jplatte** [comment]
Done! https://www.ruma.io/projects/
